bakery/urls.py
from django.urls import path

from .views import register_user, register_order


app_name = 'bakery'

urlpatterns = [
    path('user/', register_user, name='user_reg'),
    path('order/', register_order, name='register_order'),
]

cakeshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import render

from bakery.views import profile, payment_update, index, logout_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='start_page'),
    path('api-auth/', include('rest_framework.urls')),
    path('lk', profile, name='lk'),
    path('logout', logout_view, name='logout'),
    path('register/', include('bakery.urls'), name='reg'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/lk-order.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="Style.css">
	<!-- Для разработки: -->
	<script src="https://unpkg.com/vue@3"></script>
	<!-- Для продакшина: -->
	<!-- <script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script> -->
	<script src="https://unpkg.com/vee-validate"></script>
	<title>Личный кабинет</title>
</head>
<body>
<nav class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-4">
	<div class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="#">
			<img src="img/Logo.svg" alt="CakeBake">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step3">Создать торт</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step2">Каталог</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#step4">Оплата и доставка</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="./index.html#Contacts">Контакты</a>
				</li>
				<li class="nav-item d-block d-xl-flex flex-column align-items-end me-5">
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">8 (495) 000-00-00</small>
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">Пн - Вс 10:00—20:00</small>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="img/shopping-cart.svg" alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src="img/user.svg" alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter cake_grey fs_12" href="#">
						Ирина
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div class="container mt-header mb-5">
	<div class="row mt-5">
		<div class="col-12 col-xxl-6 d-flex justify-content-center">
			<div><img src="img/Cake2.png" alt=""></div>
		</div>
		<div class="col-12 col-xxl-6 d-flex flex-column justify-content-center align-items-center align-items-xxl-start" id="LK">
			<form class="d-none">
				<input v-model="Name" name="NAME">
				<input v-model="Phone" name="PHONE">
				<input v-model="Email" name="EMAIL">
				<button type="submit" ref="HiddenFormSubmit">Apply Changes</button>
			</form>
			<v-form :validation-schema="Schema" @submit="ApplyChanges">
				<div class="d-flex w-100 justify-content-center justify-content-xxl-between align-items-center">
					<h1 class="font_Gogh fs_40 cake_blue">Личный кабинет</h1>
					<button v-if="!Edit" @click="Edit = true" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-pencil-fill" viewBox="0 0 16 16">
							<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</button>
					<button v-if="Edit" type="submit" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-check-lg" viewBox="0 0 16 16">
							<path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
						</svg>
					</button>
				</div>
				<div class="d-flex">
					<ul class="list-group">
						<li class="list-group-item border-0 ps-0">
							<span class="fs_40 cake_blue">Имя</span>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Телефон</h1>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Почта</h1>
						</li>
					</ul>
					<ul class="list-group">
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Name" type="text" name="name_format" id="name" :readonly="!Edit" class="form-control my-2 i cake__textinput"></v-field>
							<error-message name="name_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Phone" type="text" name="phone_format" id="phone" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="phone_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
						<li class="list-group-item border-0 py-61 position-relative">
							<v-field v-model="Email" type="text" name="email_format" id="email" :readonly="!Edit" class="form-control my-2 cake__textinput"></v-field>
							<error-message name="email_format" class="position-absolute bottom-0 cake_pink fs_12"></error-message>
						</li>
					</ul>
				</div>
			</v-form>
			<h2 class="fs_40 cake_pink mt-5">Мои заказы</h2>
			<section class="my-2">
				<span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal2">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
					</svg>
					<span class="ms-1">#2239400223 Свадебный торт “VIP”</span>
				</span>
				<aside class="modal fade" id="OrderModal2" tabindex="-1" aria-labelledby="ModalLabel2" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title cake_pink" id="ModalLabel2">#2239400223 Свадебный торт “VIP””</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								<span class="cake_blue">Уровней: 1</span><br>
								<span class="cake_blue">Форма: круг</span><br>
								<span class="cake_blue">Топпинг: без</span><br>
								<span class="cake_blue">Ягоды: нет</span><br>
								<span class="cake_blue">Декор: нет</span><br>
								<span class="cake_blue">Без надписи</span><br>
								<span class="cake_pink">Цена: 1000₽</span>
							</div>
							<div class="modal-footer d-flex justify-content-between">
								<span class="cake_blue d-flex">Статус: В доставке</span>
								<span class="cake_blue d-flex align-items-center">Время доставки: ?</span>
							</div>
						</div>
					</div>
				</aside>
			</section>
			<section class="my-2">
				<span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal1">
					<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
						<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
					</svg>
					<span class="ms-1">#45575879537 Торт “Черепаха”</span>
				</span>
				<aside class="modal fade" id="OrderModal1" tabindex="-1" aria-labelledby="ModalLabel1" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title cake_pink" id="ModalLabel1">#45575879537 Торт “Черепаха”</h5>
								<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
							</div>
							<div class="modal-body">
								<span class="cake_blue">Уровней: 2</span><br>
								<span class="cake_blue">Форма: квадрат</span><br>
								<span class="cake_blue">Топпинг: белый соус</span><br>
								<span class="cake_blue">Ягоды: безе</span><br>
								<span class="cake_blue">Декор: нет</span><br>
								<span class="cake_blue">С днём рождения</span><br>
								<span class="cake_pink">Цена: 2550₽</span>
							</div>
							<div class="modal-footer d-flex justify-content-between">
								<span class="cake_blue">Статус: Выполнен</span>
								<span class="cake_blue">Время доставки: ?</span>
							</div>
						</div>
					</div>
				</aside>
			</section>

			<button class="btn text-white rounded-pill align-self-end px-5 mt-3 shadow-none cake__button cake__bg_pink">Выйти</button>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="lk.js"></script>
</body>
</html>

templates/lk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href='{% static "Style.css" %}'>
	<!-- Для разработки: -->
	<!-- <script src="https://unpkg.com/vue@3"></script> -->
	<!-- Для продакшина: -->
	<script src="https://unpkg.com/vue@3/dist/vue.global.prod.js"></script>
	<script src="https://unpkg.com/vee-validate"></script>
	<title>Личный кабинет</title>
</head>
<body>
<header class="navbar navbar-expand-xl navbar-light fixed-top bg-white py-4">
	<nav class="container">
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'start_page' %}">
			<img src='{% static "img/Logo.svg" %}' alt="CakeBake">
		</a>
		<div class="collapse navbar-collapse justify-content-end" id="navbar">
			<ul class="navbar-nav">
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="{% url 'start_page' %}#step3">Создать торт</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="{% url 'start_page' %}#step2">Каталог</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="{% url 'start_page' %}#step4">Оплата и доставка</a>
				</li>
				<li class="nav-item me-5">
					<a class="nav-link fw-lighter cake_blue" href="{% url 'start_page' %}#Contacts">Контакты</a>
				</li>
				<li class="nav-item d-block d-xl-flex flex-column align-items-end me-5">
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">8 (495) 000-00-00</small>
					<small class="fw-lighter text-decoration-none fs_12 cake_blue">Пн - Вс 10:00—20:00</small>
				</li>
				<li class="nav-item d-flex align-items-center">
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src='{% static "img/shopping-cart.svg" %}' alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter me-1 cake_blue position-relative" href="#">
						<img src='{% static "img/user.svg" %}' alt="">
						<span class="position-absolute translate-middle badge rounded-pill cake__bg_pink fs_8">1</span>
					</a>
					<a class="nav-link fw-lighter cake_grey fs_12" href="#">
						{% if not user.name %}
							Имя не указано
						{% else %}
							{{ user.name }}
						{% endif %}
					</a>
				</li>
			</ul>
		</div>
	</nav>
</header>
<div class="container mt-header mb-5">
	<div class="row mt-5">
		<div class="col-12 col-xxl-6 d-flex justify-content-center">
			<div><img src='{% static "img/Cake2.png" %}' alt=""></div>
		</div>
		<div class="col-12 col-xxl-6 d-flex flex-column justify-content-center align-items-center align-items-xxl-start" id="LK">
			<form class="d-none">
				<input v-model="Name" name="NAME">
				<input v-model="Phone" name="PHONE">
				<input v-model="Email" name="EMAIL">
				<button type="submit" ref="HiddenFormSubmit">Apply Changes</button>
			</form>
			<form method="post" action="{% url 'bakery:user_reg' %}">{% csrf_token %}
				<div class="d-flex w-100 justify-content-center justify-content-xxl-between align-items-center">
					<h1 class="font_Gogh fs_40 cake_blue">Личный кабинет</h1>
					<button v-if="!Edit" @click="Edit = true" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-pencil-fill" viewBox="0 0 16 16">
							<path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
						</svg>
					</button>
					<button v-if="Edit" type="submit" class="btn shadow-none align-self-center">
						<svg xmlns="http://www.w3.org/2000/svg" width="27" height="27" fill="#DA87A9" style="border-bottom: #DA87A9 2px solid" class="bi bi-check-lg" viewBox="0 0 16 16">
							<path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
						</svg>
					</button>
				</div>
				<div class="d-flex">
					<ul class="list-group">
						<li class="list-group-item border-0 ps-0">
							<span class="fs_40 cake_blue">Имя</span>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Телефон</h1>
						</li>
						<li class="list-group-item border-0 ps-0">
							<h1 class="fs_40 cake_blue">Почта</h1>
						</li>
					</ul>
					<ul class="list-group">
						<li v-if="Edit" class="list-group-item border-0 py-61 position-relative">
							<input name="name" id="name_input" class="form-control my-2 i cake__textinput" value="{{user.name}}"></input>
						</li>
						<li v-if="Edit" class="list-group-item border-0 py-61 position-relative">
							<input name="phone" id="phone_input" class="form-control my-2 i cake__textinput" value="{{user.phone}}"></input>
						</li>
						<li v-if="Edit" class="list-group-item border-0 py-61 position-relative">
							<input name="email" id="email_input" class="form-control my-2 i cake__textinput" value="{{user.email}}"></input>
						</li>

						<li v-if="!Edit" class="list-group-item border-0 py-61 position-relative">
							<div id="name" class="form-control my-2 i cake__textinput">
								{% if not user.name %}
									Имя не указано
								{% else %}
									{{ user.name }}
								{% endif %}
							</div>
						</li>
						<li v-if="!Edit" class="list-group-item border-0 py-61 position-relative">
							<div id="phone" class="form-control my-2 i cake__textinput"> {{user}} </div>
						</li>
						<li v-if="!Edit" class="list-group-item border-0 py-61 position-relative">
							<div id="email" class="form-control my-2 i cake__textinput">
								{% if not user.email %}
									Почта не указана
								{% else %}
									{{ user.email }}
								{% endif %}
							</div>
						</li>
					</ul>
				</div>
			</form>
			<h2 class="fs_40 cake_pink mt-5">Мои заказы</h2>

			{% if not orders %}
				<span class="cake_grey">У вас еще нет заказов.</span>
				<p class="cake_grey">Вы можете добавить торт из <a href="{% url 'start_page' %}#step2" class="text-decoration-none cake_pink">Каталога</a> или <a href="{% url 'start_page' %}#step3" class="text-decoration-none cake_pink">Создать свой</a>.</p>
			{% else %}
				{% for order in orders %}
					<section class="my-2">
						<span class="cake_blue lk__order d-flex" data-bs-toggle="modal" data-bs-target="#OrderModal2">
							<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
								<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
							</svg>
							<span class="ms-1">#{{order.id}}</span>
						</span>
						<aside class="modal fade" id="OrderModal2" tabindex="-1" aria-labelledby="ModalLabel2" aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h5 class="modal-title cake_pink" id="ModalLabel2">#{{order.id}}</h5>
										<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
									</div>
									{% for cake in order.cakes.all %}
										<div class="modal-body">
											<span class="cake_blue">Уровней: {{cake.levels}}</span><br>
											<span class="cake_blue">Форма: {{cake.form}}</span><br>
											<span class="cake_blue">Топпинг: {{cake.topping}}</span><br>
											<span class="cake_blue">Ягоды: {% if cake.berries %}{{cake.berries}}{% else %}Без ягод{% endif %}</span><br>
											<span class="cake_blue">Декор: {% if cake.decor %}{{cake.deocr}}{% else %}Без декора{% endif %}</span><br>
											<span class="cake_blue">Надпись: {% if cake.words %}{{cake.words}}{% else %}Без Надписи{% endif %}</span><br>
											<span class="cake_pink">Цена: {{cake.cost}}₽</span>
										</div>
									{% endfor %}
									<div class="modal-footer d-flex justify-content-between">
										<span class="cake_blue d-flex">Статус: В доставке</span>
										<span class="cake_blue d-flex align-items-center">Время доставки: ?</span>
									</div>
								</div>
							</div>
						</aside>
					</section>
				{% endfor %}
			{% endif %}
			<span class="cake_grey">Есть вопросы?</span>
			<span class="cake_grey">Воспользуйтесь нашим <a href="https://vk.com/devmanorg" class="text-decoration-none cake_pink">чат-ботом</a>.</span>
			<a href="{% url 'logout' %}" class="btn text-white rounded-pill align-self-end px-5 mt-3 shadow-none cake__button cake__bg_pink" >Выйти</a>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src='{% static "lk.js" %}'></script>
</body>
</html>